# Basic Dependabot configuration for npm dependencies
version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package.json or Gemfile
    schedule:
      interval: "weekly" # Possible values: daily, weekly, monthly